# Generated by Django 5.1.7 on 2025-03-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objetdefectueux',
            options={'verbose_name': 'Objet défectueux', 'verbose_name_plural': 'Objets défectueux'},
        ),
        migrations.RenameField(
            model_name='objetdefectueux',
            old_name='date_inspection',
            new_name='inspection_date',
        ),
        migrations.AlterField(
            model_name='objetdefectueux',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], default='pending', max_length=15),
        ),
    ]
