# Generated by Django 5.1.7 on 2025-03-27 10:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_objetdefectueux_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Created Object'), ('UPDATE', 'Updated Object'), ('DELETE', 'Deleted Object'), ('RESTORE', 'Restored Object'), ('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('VIEW', 'Viewed Object')], max_length=20),
        ),
        migrations.CreateModel(
            name='ImageAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='defect_images/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('prediction', models.FloatField(null=True)),
                ('is_defective', models.BooleanField(default=False)),
                ('confidence_score', models.FloatField(null=True)),
                ('analysis_date', models.DateTimeField(auto_now_add=True)),
                ('recommendations', models.TextField(blank=True)),
                ('objet_defectueux', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.objetdefectueux')),
            ],
            options={
                'ordering': ['-analysis_date'],
            },
        ),
    ]
