# Generated by Django 5.1.7 on 2025-03-27 14:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_imageanalysis_prediction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageanalysis',
            name='annotated_image',
            field=models.ImageField(blank=True, null=True, upload_to='defect_images/annotated/'),
        ),
        migrations.AlterField(
            model_name='imageanalysis',
            name='image',
            field=models.ImageField(upload_to='defect_images/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])]),
        ),
    ]
