# Generated by Django 5.1.7 on 2025-03-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_imageanalysis_annotated_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageanalysis',
            name='analysis_type',
            field=models.CharField(choices=[('YOLO', 'YOLO Analysis'), ('BASIC', 'Basic Analysis')], default='BASIC', max_length=10),
        ),
    ]
